### ISSUE TITLE
Reorganize data

### ISSUE THREAD

**Issue by quadfather85** [leesharpe/nfldata#1]
In running the following I get `Error: by can't contain join column season which is missing from LHS`

`rookie_data <- plays %>%
  filter(!is.na(epa) & play_type %in% c("pass","run")) %>% 
  mutate(short_name =
           ifelse(is.na(passer_player_name),rusher_player_name,passer_player_name)) %>% 
  inner_join(rookie_qbs,by = c("season" = "season","posteam" = "team")) %>% 
  filter(substr(short_name,1,1) == substr(name,1,1)) %>% 
  filter(substr(short_name,str_locate(short_name,"\\.")+1,100) == 
           substr(name,str_locate(name," ")+1,100)) %>% 
  inner_join(logos,by = c("posteam"="team")) %>% 
  group_by(season,posteam,short_name,url) %>% 
  summarize(stddev=sd(epa),epa=mean(epa),count=n()) %>% 
  filter(count >= 100)`

**Comment by leesharpe** [comment]
Great catch! I made an assumption about changes to the plays data people would have made when I wrote this, which was poor. A new version I just checked in adds in the data it needs itself and appears to resolve the issue!
