### ISSUE TITLE
total_line Incorrect for 3 Games

### ISSUE THREAD

**Issue by agad495** [leesharpe/nfldata#11]
Hi Lee,

Thank you so much for providing so many great resources on here!

Just wanted to make you aware of 3 total_lines that are incorrect (I'm guessing they're the 1H totals) in games.csv:

- 2006_19_SEA_CHI:
Currently: 20.0
Should be: 37.5

- 2006_05_DET_MIN:
Currently: 20.5
Should be: 41.0

- 2006_05_TEN_IND:
Currently: 23.5
Should be: 47.5

The "should be" lines are from pro-football-reference.com.

Thanks!

**Comment by leesharpe** [comment]
Great catch! Fixed with this change:

https://github.com/leesharpe/nfldata/commit/5b70e35780013e8922f9fd39c9f533183308f342
