### ISSUE TITLE
Fix for passer_player_name doesn't work

### ISSUE THREAD

**Issue by mrcaseb** [leesharpe/nfldata#6]
It looks like the code in line 170 isn't working as desired. The value of passer_player_name remains `NA` when executing it. 
Compared to Ben's code on [https://gist.github.com/guga31bb/5634562c5a2a7b1e9961ac9b6c568701](url) the difference is an additional blank space in line 170 right before "pass". 

I have tested it without the blank space and it looks like this is fixing the problem.

https://github.com/leesharpe/nfldata/blob/6f8e79aa61c061ee40cad104e5c86c5b61e794e5/code/plays-functions.R#L169-L171

**Comment by mrcaseb** [comment]
To make it more clear I tried to create a working example to reproduce what I mean.

In the Code below I did it for the 2018 season but it is the same for every season. 

The dataframe `with_blank` looks like this:
<img width="789" alt="Bildschirmfoto 2020-02-29 um 08 53 43" src="https://user-images.githubusercontent.com/38586519/75603681-12e6c600-5ad1-11ea-846b-87aa1c99bddd.png">

The dataframe `no_blank` looks like this:
<img width="793" alt="Bildschirmfoto 2020-02-29 um 08 55 20" src="https://user-images.githubusercontent.com/38586519/75603695-3c9fed00-5ad1-11ea-9345-6b82b3ed96e1.png">

I hope this helps...

```R
library(tidyverse)
library(na.tools)

pbp <- read_csv("https://raw.githubusercontent.com/ryurko/nflscrapR-data/master/play_by_play_data/regular_season/reg_pbp_2018.csv")

with_blank <- pbp %>%
  mutate(
    pass=ifelse(str_detect(desc,"( pass)|(sacked)|(scramble)"),1,0),
    passer_player_name=ifelse(play_type == "no_play" & pass == 1, 
                              str_extract(desc,"(?<=\\s)[A-Z][a-z]*\\.\\s?[A-Z][A-z]+(\\s(I{2,3})|(IV))?(?=\\s(( pass)|(sack)|(scramble)))"),
                              passer_player_name),
    name=ifelse(!is.na(passer_player_name),passer_player_name,rusher_player_name)
  ) %>%
  filter(play_type=="no_play" & pass==1) %>%
  select(game_id, play_id, desc, pass, passer_player_name, name)
  
no_blank <- pbp %>%
  mutate(
    pass=ifelse(str_detect(desc,"( pass)|(sacked)|(scramble)"),1,0),
    passer_player_name=ifelse(play_type == "no_play" & pass == 1, 
                              str_extract(desc,"(?<=\\s)[A-Z][a-z]*\\.\\s?[A-Z][A-z]+(\\s(I{2,3})|(IV))?(?=\\s((pass)|(sack)|(scramble)))"),
                              passer_player_name),
    name=ifelse(!is.na(passer_player_name),passer_player_name,rusher_player_name)
  ) %>%
  filter(play_type=="no_play" & pass==1) %>%
  select(game_id, play_id, desc, pass, passer_player_name, name)`

**Comment by leesharpe** [comment]
Great call out. Now fixed.
