### ISSUE TITLE
fix_team_abbreviations function incomplete for 1999-2008 data

### ISSUE THREAD

**Issue by mrcaseb** [leesharpe/nfldata#7]
When applying the game data in the following function the `inner_join` in line 149 ensures that only data within the games.csv remain in the pbp dataset. 

https://github.com/leesharpe/nfldata/blob/0990adaa4fdb4e891e96cc293444e262d35dcba9/code/plays-functions.R#L138-L152

To not accidentally delete games with different/old team abbreviations you run the following function before applying the game data.

https://github.com/leesharpe/nfldata/blob/0990adaa4fdb4e891e96cc293444e262d35dcba9/code/plays-functions.R#L113-L133

The problem is there are many "new" old team abbreviations in the 1999-2008 datasets like "ARZ", "BLT" or "CLV" which leads to games of these teams being lost at the above mentioned inner_join. If I have done it correct we are talking about 278 games being deleted between 1999 and 2008 (see the attached list missing_games.txt). To fix this you need to check the old team abbreveations in the list and add them to the fix_team_abbreviations function.

Additionally I think you should drop the `old_to_new` option since the team abbreviations must fit the used abbreviations in your games.csv. Alternatively you could change the `inner_join` to 
`inner_join(games,by="game_id")` to allow team abbreviations not included in your games.csv

[missing_games.txt](https://github.com/leesharpe/nfldata/files/4286868/missing_games.txt)

**Comment by mrcaseb** [comment]
I would suggest the following updates to the mentioned functions
```R
fix_team_abbreviations <- function(p,old_to_new=FALSE)
{
  for (col in grep_col("team",p))
  {
    x <- p %>% pull(col)
    if (typeof(x) == "character")
    {
      p[,col] <- case_when(
        x == "ARZ" ~ "ARI",
        x == "BLT" ~ "BAL",
        x == "CLV" ~ "CLE",
        x == "HST" ~ "HOU",
        x == "JAC" ~ "JAX",
        x == "LA"  ~ "LAR",
        x == "SD"  & old_to_new ~ "LAC",
        x == "SL"  ~ "STL",
        x == "STL" & old_to_new ~ "LAR",
        x == "OAK" & old_to_new ~ "LV",
        TRUE ~ x)
    }
  }
  return(p)
}
```
```R
apply_game_data <- function(p)
{
  if (!("alt_game_id" %in% colnames(p)))  # already included, don't reapply
  {
    report("Applying game data")
    if (!exists("games"))
      games <- read_csv("http://www.habitatring.com/games.csv")
    games <- games %>%
      mutate(game_id=as.character(game_id))
    p <- p %>% 
      fix_inconsistent_data_types() %>% 
      left_join(games,by="game_id") %>% # with left_join games missing in games.csv will be kept with season==NA
      select(-away_team.y, -home_team.y) %>% # since we are left joining away_team and home_team are duplicated 
      rename(home_team=home_team.x, away_team=away_team.x)
  }
  return(p)
}
```

**Comment by mrcaseb** [comment]
Unfortunately my suggested fix for the team abbreviations didn't work for St. Louis with option `old_to_new=TRUE` since my intended behavior SL -> STL -> LAR in one run did not work. Sorry.

New suggestion (successfully tested):
```R
fix_team_abbreviations <- function(p,old_to_new=FALSE)
{
  for (col in grep_col("team",p))
  {
    x <- p %>% pull(col)
    if (typeof(x) == "character")
    {
      p[,col] <- case_when(
        x == "ARZ" ~ "ARI",
        x == "BLT" ~ "BAL",
        x == "CLV" ~ "CLE",
        x == "HST" ~ "HOU",
        x == "JAC" ~ "JAX",
        x == "LA"  ~ "LAR",
        x == "SD"  & old_to_new ~ "LAC",
        x == "SL"  & old_to_new ~ "LAR",
        x == "SL"  & !old_to_new ~ "STL",
        x == "STL" & old_to_new ~ "LAR",
        x == "OAK" & old_to_new ~ "LV",
        TRUE ~ x)
    }
  }
  return(p)
}
```

**Comment by leesharpe** [comment]
I was unable to find this looking through my code. However, it's at worst harmless and at best helpful, so I'm taking it.
