### ISSUE TITLE
Air_is_zero wrong binary value

### ISSUE THREAD

**Issue by mrcaseb** [leesharpe/nfldata#8]
The mutation air_is_zero in my opinion gets the wrong binary value in the below marked lines. Although it doesn’t make a difference for the cp_model this maybe should be fixed. 

https://github.com/leesharpe/nfldata/blob/0990adaa4fdb4e891e96cc293444e262d35dcba9/code/plays-functions.R#L299

https://github.com/leesharpe/nfldata/blob/0990adaa4fdb4e891e96cc293444e262d35dcba9/code/plays-functions.R#L310

**Comment by leesharpe** [comment]
This has now been reversed.
