### ISSUE TITLE
Baldwin Mutations Error - Passer EPA

### ISSUE THREAD

**Issue by z-feldman** [leesharpe/nfldata#9]
Hey Lee,

Got this error when running of playdata: 
# Line of code ran
if (baldwin_mutations) plays <- apply_baldwin_mutations(plays)

[1] "2020-03-16 12:30:14: Applying Ben Baldwin mutations"

# Error
Error in ifelse(!is.na(passer_epa), passer_epa, ifelse(!is.na(epa) & pass ==  : 
  object 'passer_epa' not found
Called from: ifelse(!is.na(passer_epa), passer_epa, ifelse(!is.na(epa) & pass == 
    1, epa, NA))
Browse[1]> Q

Looks like it's throwing the error on line 222-225 in plays-functions where p and wr_fumbled are joined then passer_epa is mutated. If I find the error I'll let you know thanks

Zach

**Comment by z-feldman** [comment]
lol I didn't know hashtag made the text big and bold I was trying to do an R comment

**Comment by z-feldman** [comment]
It looks like after the join of p and wr_fumbled, it's trying to mutate passer epa before it checks if passer_epa.y exists. I ran the if statement in plays-functions line 227, then ran the mutate in line 224 and did not get an error, so I think that's the issue.

**Comment by leesharpe** [comment]
This has now been resolved, there's an explicit check for passer_epa.y before p is changed.
